### ISSUE TITLE
update to 22.05 and new parallel tools new version

### ISSUE THREAD

**Issue by sandangel** [wegank/nixos-config#2]
Hi, could you add an update for new version of parallel tools (17.1.3-51565), as well as patch for kernel 5.18? I'm trying the kernel 5.18 but parallel tools I copied from your nix config can not be built anymore.

**Comment by wegank** [comment]
I've updated the package. Let me know if this works for you now.

**Comment by sandangel** [comment]
Hi @wegank thanks for the update, I think it can compile, but somehow I'm experiencing some keyboard freezing sometimes. Also the key sometime stuck and it prints lots of characters on the screen. I'm using gnome wayland. maybe a kernel bug. I'm not sure. Are you experiencing the same? Probably I might just switch back to 5.17

**Comment by wegank** [comment]
I don't have this problem on my machine. Strange though.

**Comment by sandangel** [comment]
I switched back to 5.17, will test for 1 day to see if I still have the problem. anyway, thanks a lot for updating this. I will report again if I found the issue still exists.

**Comment by sandangel** [comment]
I don't see the weird keyboard issue anymore after switching back to kernel 5.17. Probably a bug, since Parallels doesn't support kernel 5.18 yet, but I have no idea. I have couples of keymaps defining on Parallels and on Karabiner. Maybe that's why I see the bug. You can check my nix-config repo for reference. https://github.com/sandangel/nixos-config/tree/main/pkgs/parallels-tools

**Comment by sandangel** [comment]
anyway, thanks a lot for putting a patch on this.
